### ISSUE TITLE
Cannot select installation location of Derail Valley

### ISSUE THREAD

**Issue by CzechVhrsaler** [AyrA/DVMusicEdit#1]
I either cannot find how to, or cannot set the location of my installation of Derail Valley. This prevents me from using the program.

**Comment by AyrA** [comment]
What's your environment (Windows version, steam installation, DV path)?

This application tries to autodetect the game by scanning all your local steam game library directories.

**Comment by CzechVhrsaler** [comment]
I'm Running Windows 10. My DV Is In My Second Lib (In D:) At "D:\SteamLibrary2\steamapps\common\Derail Valley"

**Comment by AyrA** [comment]
This is weird, because I have a similar setup (Win10 with DV not in my primary library either). Anyways, [I added v1.1 to gitload](https://gitload.net/AyrA/DVMusicEdit) that should fix this issue. If DV cannot be found, you're presented with a folder browser to manually select the directory.

**Comment by AyrA** [comment]
Note that your selection is currently not saved, so you have to do this every time you run the application as of now. I will probably add a feature to remember the selected path in the next version.

**Comment by CzechVhrsaler** [comment]
Thank You For Being So Urgent. Your Help And Speed Is Greatly Appreciated!

**Comment by AyrA** [comment]
Does manually selecting the installation work for you now?

**Comment by CzechVhrsaler** [comment]
Yes. However The Titles That Can Be Put On The Tracks You Install Do Not Show In Game.

**Comment by AyrA** [comment]
It's possible that the boombox is ignoring your custom title if the track itself has a title attribute. It definitely does this for the webradio streams, but I'm not sure about the tapes.

**Comment by CzechVhrsaler** [comment]
It Does Do It For The Tapes. Is There Any Way To Rectify This Issue?

**Comment by AyrA** [comment]
You could rename the files to match the title you want them to have. I think DV doesn't decodes the metadata and also ignores the Title you set. It may be simply based on the file name.

**Comment by CzechVhrsaler** [comment]
This Is Not Optimal But If It Is The Only Choice Than I Suppose It Will Have To Do. Thank You For Your Help.
