### ISSUE TITLE
Problem with URL format

### ISSUE THREAD

**Issue by shmbry** [AyrA/DVMusicEdit#2]
I am having problems finding the correct URL format at:
https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3#file-bbc-radio-lstn-hls-m3u
The station plays when the play button is pressed in DVMusicEdit.exe but the station does not play on the boombox in game.

**Comment by AyrA** [comment]
The links in that file are all .m3u8 files. These do not contain a single audio file but chunks of files that have to be streamed repeatedly. (Wikipedia: [HTTP Live Streaming](https://en.wikipedia.org/wiki/HTTP_Live_Streaming?useskin=vector)).

FFmpeg understands this type of stream, so it works in the playlist editor, but the DV game does not understands them. You have to find a stream that directly outputs ogg or mp3 data.
