### ISSUE TITLE
m4a files don't work

### ISSUE THREAD

**Issue by sunny7611** [AyrA/DVMusicEdit#3]
i have ffmpeg downloaded and it won't let me import m4a files to a playlist

**Comment by AyrA** [comment]
In the file dialog, switch the file type to "all files" and see if you can add your files then

![image](https://github.com/user-attachments/assets/5ec56604-f276-4b35-b72c-5e51b0cfb5d1)

**Comment by sunny7611** [comment]
> In the file dialog, switch the file type to "all files" and see if you can add your files then
> 
> ![image](https://private-user-images.githubusercontent.com/1301960/389293547-5ec56604-f276-4b35-b72c-5e51b0cfb5d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NjA2MDEsIm5iZiI6MTczMjY2MDMwMSwicGF0aCI6Ii8xMzAxOTYwLzM4OTI5MzU0Ny01ZWM1NjYwNC1mMjc2LTRiMzUtYjcyYy01ZTUxYjBjZmI1ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMjIzMTQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDFjNWIyMjBiYTc2NjJjMmM3ZTE4Y2FjZjJmOGNkZjZhMmRmMzc3YzQ3ZDQ5Nzg1NmMxZjU3NWNmMWIzNDRkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.WqxmSbUGYUzVvLnBpBk_8-JF1Yg1O11rZtS95idtQnA)

thanks that worked

**Comment by AyrA** [comment]
A new version was released, that among other things supports the m4a file extension natively now.
